# -*- encoding: utf-8 -*-

ARTICLE_PER_PAGE_DEFAULT = 20
ARTICLE_PER_PAGE_NOTICE = 5


MEMBER_HEAD = 0
MEMBER_WEB = 1
MEMBER_LINUX = 2
MEMBER_WINDOW = 3
MEMBER_PROBATION = 4
MEMBER_DISPATCHED = 5
MEMBER_OB = 6
MEMBER_TYPE = ( 
	(MEMBER_HEAD, 'Head'),
	(MEMBER_WEB, 'Web'),
	(MEMBER_LINUX, 'Linux'),
	(MEMBER_WINDOW, 'Window'),
	(MEMBER_PROBATION, 'Probation'),
	(MEMBER_DISPATCHED, 'Dispatched'),
	(MEMBER_OB, 'OB'),
)
